version: '3'

services:
        shop-server:
                image: techpoc/shop-server-h2mem:1.0
                volumes:
                        - /c/Users/manish/PetStore:/root/PetStore
                network_mode: "host"

        shop-client:
                depends_on:
                        - shop-server
                image: techpoc/shop-client:1.0
                volumes:
                        - /c/Users/manish/PetClient:/root/PetClient
                network_mode: "host"
                healthcheck:
                        test: ["CMD", "curl", "-f", "http://localhost:8081/pet-services/petWebService/pet/ping"]
                        interval: 5s 
                        timeout: 10s
                        retries: 2

        shop-gui:
                depends_on:
                        - shop-server
                        - shop-client
                image: techpoc/shop-gui:1.0
                network_mode: "host" 
